owmbeat:

  period: 1m

  appid: "yourappid"

  regions:
    - region:
      enabled: true
      name: "Slovakia"
      description: "Somewhere in Europe"
      lon-left: 16
      lat-bottom: 47
      lon-right: 23
      lat-top: 50
      zoom: 10

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
